### ISSUE TITLE
tracking issue

### ISSUE THREAD

**Issue by KisaragiEffective** [KisaragiEffective/origlang#19]
- [ ] 変数への再代入ができないので再代入を許可する
	- 現在でもRustのように同名の変数を宣言してシャドウすることで実質的な再代入はできなくない
- [ ] 再代入できない束縛の追加 (`var`に対して`let`であるべきか？)
- [ ] 一引数一返り値の関数を宣言できるようにする (`var add = (a) => (b) => a + b`)
- [ ] 一行コメントを許可する
- [ ] 空行を許可する
- [ ] タプルの追加
- [ ] サブタイピングの追加
	- `Int`、`Bool`、`String`の間にはそれぞれサブタイプ関係を入れない
	- [ ] トップ型の追加
- [ ] 多相な関数の追加
 	- [ ] ボトム型の追加？
- [ ] 2つ以上の引数を持つ関数の追加
- [ ] 0個の引数を持つ関数の追加
- [ ] クラシックな`switch`の追加
- [ ] `println`をimplicitにしない
- [ ] パターンマッチの追加
- [ ] 名前がついた値の組を宣言できる仕組み
- [ ] 浮動小数点数型の追加
	- [ ] `f32`の追加
	- [ ] `f64`の追加
- [ ] `i64`/`i8`/`i16`の追加
- [ ] 符号なし整数の追加
- [ ] 配列の追加
